package modelos.entidades;
// Generated 19-dic-2018 15:41:00 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EstadisticasId generated by hbm2java
 */
@Embeddable
public class EstadisticasId implements java.io.Serializable {

	private String temporada;
	private int jugador;

	public EstadisticasId() {
	}

	public EstadisticasId(String temporada, int jugador) {
		this.temporada = temporada;
		this.jugador = jugador;
	}

	@Column(name = "temporada", nullable = false, length = 5)
	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

	@Column(name = "jugador", nullable = false)
	public int getJugador() {
		return this.jugador;
	}

	public void setJugador(int jugador) {
		this.jugador = jugador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstadisticasId))
			return false;
		EstadisticasId castOther = (EstadisticasId) other;

		return ((this.getTemporada() == castOther.getTemporada()) || (this.getTemporada() != null
				&& castOther.getTemporada() != null && this.getTemporada().equals(castOther.getTemporada())))
				&& (this.getJugador() == castOther.getJugador());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTemporada() == null ? 0 : this.getTemporada().hashCode());
		result = 37 * result + this.getJugador();
		return result;
	}

}
